### PR TITLE
Allow producing <flox/channel> deprecation warning[CU-1crx0ar]

### PR DESCRIPTION
**Pull request by Infinisil**
With the move from <flox/channel> to <flox-lib/channel>, the
<flox/channel> mechanism needs a deprecation warning. This can be
implemented now by pointing `<flox/channel>` to a Nix file containing

    import <flox-lib/channel/legacy.nix>

Which when imported from a channel will produce an error like

    trace: warning: The channel "test" uses the deprecated `<flox/channel>`
    in .*/test/default.nix. Replace it with `<flox-lib/channel>` to get rid of this warning.

PR is scarier than it looks, it's just that the `default.nix` file was moved to `new.nix` with a small adjustment

- [x] I have created a test to cover the new behavior.
- [ ] I have written and updated relevant documentation, including updating this
      pull request template if necessary. Note that we try to follow the
      [Divio documentation](https://documentation.divio.com/) of documentation.

### CODE REVIEW

**Comment by bpiv400** [comment]
Task linked: [CU-1crx0ar Review: Allow producing <flox/channel> deprecation warning on flox-lib](https://app.clickup.com/t/1crx0ar)

**Comment by limeytexan** [comment]
Once everyone has updated their `default.nix` files will we be renaming `new.nix` back to `default.nix`? If so is there any way to avoid doing that? Why couldn't `<flox-lib/channel/legacy.nix>` import `./default.nix`?

**Comment by Infinisil** [comment]
@limeytexan Yeah, I also put a note on top of `new.nix` that it should be moved back to `default.nix`. The reason for doing it this way is a combination of:
- Wanting to have errors that give the user information on which channel needs to be fixed, meaning we need to inspect at least the `topdir` argument. Because of this we can't just create a `legacy.nix` with `builtins.trace "warning" (import ./default.nix)`, because such a warning can only be a static string (and we can't know where the file was imported from)
- Nix CLI arguments not propagating through files: If we had a legacy.nix looking like
  ```nix
  args: builtins.trace "warning for ${args.topdir}" (import ./default.nix args)
  ```
  we couldn't pass arguments with `--arg`/`--argstr` anymore (unless we duplicated all the arguments with `args@{ <args here> }`, which will get out of sync)

**Review by limeytexan — APPROVED** [review]
LGTM

**Pull request merged**
